#dockerfile for flask calculator app

FROM python:3.8-slim-buster
RUN sed -i 's|deb.debian.org/debian|archive.debian.org/debian|g' /etc/apt/sources.list \
 && sed -i 's|security.debian.org|archive.debian.org/debian-security|g' /etc/apt/sources.list || true \
 && apt-get update -o Acquire::Check-Valid-Until=false -y

EXPOSE 5000

COPY . /app
COPY templates /app

WORKDIR /app

RUN pip3 install -r requirements.txt

CMD ["python3", "GeometryCalcWeb.py"]